### ISSUE TITLE
MaxMind is deprecating the data format we use.

### ISSUE THREAD

**Issue by pboothe** [m-lab/etl#389]
https://dev.maxmind.com/geoip/geoip2/geolite2/

MaxMind is discontinuing the GeoLite legacy format, but will still provide a free GeoIP database. So we need to:
1. update the annotator (or some pre-processor for the annotator or a post-processor for the downloader) to understand the new format
2. update the downloader to download the new format

**Comment by gfr10598** [comment]
IIUC we are already using GeoLite2.  The new downloader is still attempting to download GeoLite legacy, but should behave well when it is no longer available.

We are currently getting our Lat/Long from the GeoLite2 data, but that will no longer work as of 2019.  So we should start downloading GeoIP2, and migrate the annotator to use that data instead of the Lat/Long data embedded within GeoLite2.

Agree with the 1H2018 timeframe.

**Comment by m-cameron** [comment]
The coordinates will be removed from Maxmind in 2019. Do you plan to support `[IP2Location LITE](https://www.ip2location.com)` free database with coordinates soon?

**Comment by mehtab11** [comment]
Obsolete/complete.
